---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeploy
  labels:
    name: testdeploy
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fbapp
  template:
    metadata:
      name: testpod
      labels:
        app: fbapp
    spec:
      containers:
      - name: testcont
        image: sravani2310/mcapp:latest
        ports:
        - containerPort: 8080
